spring.application.name=notification
server.port=8081
#EUREKA
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#email sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.config.import=optional:application-secret.properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true