spring.application.name=notification
server.port=8081
#EUREKA
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#email sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.config.import=optional:application-secret.properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#kafka
# Point to your local Kafka broker cluster
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group

# Use Error Handling Deserializers to prevent poison-pill crash loops
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate the actual parsing tasks inside the safety wrapper
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Set up trust configuration profiles and the type mapping bridge
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=com.buildcraft.inquiry.entity.CustomerInquiry:com.buildcraft.notification.dto.InquiryRequest