spring.application.name=inquiry

server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:inquiry_db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Add this at the bottom
eureka.instance.prefer-ip-address=true

# kafka
# Point to your local Kafka broker cluster
spring.kafka.producer.bootstrap-servers=localhost:9092
# Convert keys and object values into serializable strings over the network grid
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer